<?php

namespace Tests\Feature\Audit;

use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Facades\Http;
use Tests\TestCase;

class AuditEndpointTest extends TestCase
{

    use RefreshDatabase;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        User::factory(50)->create();
    }

    public function test_endpoint_auditing_without_params(){
        $response = $this->get('test/audit-without-params');
        $response->assertStatus(200);
        $this->assertDatabaseHas('audit_api_calls' , [
            'user_id' => 0,
            'incoming_url' => str_replace(['https://' , 'http://'] , '' , env('APP_URL')),
            'url_called' => route('audit.without.params'),
            'method' => 'GET',
            'request' => '[]'
        ]);
    }

    public function test_endpoint_auditing_with_params(){
        $response = $this->post('test/audit-with-params' , ['id' => 1 , 'name' => 'Test']);
        $response->assertStatus(200);
        $this->assertDatabaseHas('audit_api_calls' , [
            'user_id' => 0,
            'incoming_url' => str_replace(['https://' , 'http://'] , '' , env('APP_URL')),
            'url_called' => route('audit.with.params'),
            'method' => 'POST',
            'request' => json_encode(['id' => 1 , 'name' => 'Test'])
        ]);
    }

}
