<?php

namespace Tests\Feature\Audit;

use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class AuditTraitTest extends TestCase
{

    use RefreshDatabase;

    private static $user;
    private static $userOriginal;

    /**
     * Setup the testing and create the user
     * @return void
     */

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        self::$user = User::create(['name' => 'Test User', 'email' => 'test@test.co.uk', 'password' => 'Password-3']);
        self::$userOriginal = self::$user->getOriginal();
    }

    /**
     * Test the create function on a model
     * @return void
     */

    public function test_audit_model_create(){
        $this->assertDatabaseHas('audit_jobs' , [
            'model' => User::class,
            'model_id' => self::$user->id,
            'action' => 'Create',
            'user_id' => 0,
            'changes' => json_encode(self::$user->getAttributes())
        ]);
    }

    /**
     * Test the update function on a model
     * @return void
     */

    public function test_audit_model_update(){
        self::$user->update(['name' => 'Test User 1']);
        $this->assertDatabaseHas('audit_jobs' , [
            'model' => User::class,
            'model_id' => self::$user->id,
            'action' => 'Update',
            'user_id' => 0,
            'original' => json_encode(self::$userOriginal),
            'changes' => json_encode(self::$user->getChanges())
        ]);
    }

    /**
     * Test the delete function on a model
     * @return void
     */

    public function test_audit_model_delete(){
        self::$user->delete();
        $this->assertDatabaseHas('audit_jobs' , [
            'model' => User::class,
            'model_id' => self::$user->id,
            'action' => 'Delete',
            'user_id' => 0,
            'original' => json_encode(self::$user->getOriginal()),
            'changes' => null
        ]);
    }

}
